### PR TITLE
Update promote.py script pastebin

### PR DESCRIPTION
**Pull request by b100dian**
From Elros https://t.me/sailfishos_porters/126706

### CODE REVIEW

**Comment by mlehtima** [comment]
Is there a reason why you don't just include the file directly to faq instead of adding link to some external site? You can add for example attachments or files folder to this repo, add the file there and replace the external link with a link to that.

**Comment by b100dian** [comment]
No reason, this was just the minimal resistance change: remembered there was a dead link here, updated the link when a fresh one existed, all from the web interface. 
I'll follow your suggestion

**Comment by b100dian** [comment]
Added a link inspired from https://raw.githubusercontent.com/b100dian/hadk-faq/patch-2/resources/promote.py (changed branch and org). As opposed to markdown, rst doesn't seem to support relative links as in here https://github.blog/2013-01-31-relative-links-in-markup-files/

**Comment by elros34** [comment]
According to lbt apiurl should be https://build.sailfishos.org instead https://api.sailfishos.org

**Comment by b100dian** [comment]
> According to lbt apiurl should be https://build.sailfishos.org instead https://api.sailfishos.org

Thanks, updated.

**Review by mlehtima — APPROVED** [review]

**Pull request merged**
